user  www-data;
worker_processes auto;
pid /run/nginx.pid;

events { worker_connections 1024; }

http {
  include       /etc/nginx/mime.types;
  default_type  application/octet-stream;
  sendfile      on;
  keepalive_timeout  65;

  server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location / {
      try_files $uri /index.html;
    }

    location /fcgi-bin/ {
      include       fastcgi_params;

      fastcgi_param QUERY_STRING    $query_string;
      fastcgi_param REQUEST_METHOD  $request_method;
      fastcgi_param CONTENT_TYPE    $content_type;
      fastcgi_param CONTENT_LENGTH  0;          # для GET обязательно
      fastcgi_param SCRIPT_FILENAME app;

      fastcgi_pass 127.0.0.1:9000;              # или unix:/run/fcgi-java.sock;
      fastcgi_keep_conn on;
      fastcgi_buffering off;

    }





  }
}

